// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_identifier = {__proto__:null,query:30, select:34, select_child:40, read:46, read_attribute:50, to_number:54}
export const parser = LRParser.deserialize({
  version: 14,
  states: "&YOYQPOOOwQPO'#CaO|QQO'#CfO!RQPO'#CjO!WQPO'#ClO!]QPO'#CoO!bQPO'#CrO!gQPO'#CtO!lQPO'#CvOOQO'#DT'#DTOOQO'#Ci'#CiO!qQPO'#CiO#VQPO'#C{O#dQPO'#C|OOQO'#C{'#C{OOQO'#DS'#DSQOQPOOOOQO,58{,58{O#lQPO'#C}O#qQQO,59QOOQO,59U,59UOOQO,59W,59WOOQO,59Z,59ZOOQO,59^,59^OOQO,59`,59`OOQO,59b,59bOOQO'#DO'#DOO#yQPO,59TO$QQPO,58yOOQO,59g,59gOOQO,59h,59hOOQO,58y,58yOYQPO,59iOOQO-E6{-E6{OOQO1G.l1G.lOOQO-E6|-E6|OOQO1G.o1G.oOOQO1G.e1G.eOOQO1G/T1G/TO$VQQO'#C|",
  stateData: "$b~OuOSPOS~OUPOXQO_ROaSOdTOgUOiVOkWOlZO~OSaO~OZbO~OUdO~ObeO~OefO~ObgO~OUhO~ObiO~O_ROaSOdTOgUOiVOkWO~OVlOXQOlZO~P!qOnoOspX~O[pO~OWrOZbO~OmtO~P!qOXQO~OnoOWpXZpX~O",
  goto: "#YxPPPyP}PPPP!RPP!]!fP!fPP!fPP!fP!fP!fPPPPyy!m!sPPP!y#PT_OpT[OpS^OpQm[RulQ]OQn[RwpZXOZ[kpQcQRqcQkZRskQ`ORvpUYO[pTjZk",
  nodeNames: "⚠ Comment Query ArrayBlock > BlockPrefix String [ } { ObjectBlockNoPrefix Key = ExpressionBlockNoPrefix QueryStatement query SelectStatement select VariableName SelectChildStatement select_child Integer ReadStatement read ReadAttributeStatement read_attribute ToNumberStatement to_number ( ) ] ObjectBlock ExpressionBlock",
  maxTerm: 40,
  nodeProps: [
    ["openedBy", 8,"{"],
    ["closedBy", 9,"}"]
  ],
  skippedNodes: [0,1],
  repeatNodeCount: 2,
  tokenData: "'b~RiX^!ppq!prs#exy$uyz$z!P!Q%P!Q![%n![!]%v!_!`&b!`!a&g!c!}&l!}#O&|#P#Q'R#R#S&l#T#o&l#o#p'W#q#r']#y#z!p$f$g!p#BY#BZ!p$IS$I_!p$I|$JO!p$JT$JU!p$KV$KW!p&FU&FV!p~!uYu~X^!ppq!p#y#z!p$f$g!p#BY#BZ!p$IS$I_!p$I|$JO!p$JT$JU!p$KV$KW!p&FU&FV!p~#hWOY#eZr#ers$Qsw#ex#O#e#P;'S#e;'S;=`$o<%lO#e~$VWU~OY#eZr#ers$Qsw#ex#O#e#P;'S#e;'S;=`$o<%lO#e~$rP;=`<%l#e~$zOl~~%POm~~%SP!P!Q%V~%[SP~OY%VZ;'S%V;'S;=`%h<%lO%V~%kP;=`<%l%V~%sPe~!Q![%n~%yR!c!}&S#R#S&S#T#o&S~&XRb~!c!}&S#R#S&S#T#o&S~&gO[~~&lOS~R&sRZQxP!c!}&l#R#S&l#T#o&l~'ROV~~'WOn~~']OX~~'bOW~",
  tokenizers: [0, 1],
  topRules: {"Query":[0,2]},
  specialized: [{term: 40, get: value => spec_identifier[value] || -1}],
  tokenPrec: 0
})
